INSERT INTO employees VALUES (1,'Nisha@gmail.com','test1','Velumani'),
  (2,'two@gmail.com','test2','user two'),
  (3,'three@gmail.com','test3','user one'),
  (4,'Radha@gmail.com','Radha','semalaiappan'),
  (5,'Rajasekaran.@gmail.com','Rajasekaran','Rajendran'),
  (6,'six@gmail.com','test6','user six'),
  (7,'seven@gmail.com','test7','user seven'),
  (8,'eight@gmail.com','test8','user eight'),
  (9,'nine@gmail.com','test9','user nine'),
  (10,'ten@gmail.com','test10','user ten');
